<div id="block-<?php echo $this->blockId; ?>" class="item-list region <?php echo $this->regionClass; ?> <?php echo $this->classes ?>" data-target-region-id="<?php echo $this->targetID; ?>">
    <?php if ($this->hasTitle): ?>
        <h2><?php echo $this->title; ?></h2>
    <?php endif; ?>
    <?php if ($this->hasIntroduction): ?>
        <div class='block-introduction'>
            <?php echo $this->introduction; ?>
        </div>
    <?php endif; ?>
    <?php if ($this->hasPages): ?>
        <ul>
            <?php foreach($this->pages as $page): ?>
                <li><a href='<?php echo $page['o:url']; ?>'><?php echo $page['o:title']; ?></a></li>
            <?php endforeach ?>
        </ul>
    <?php endif; ?>
</div>