<?php
    $item = $attachment->item();

    $media = null;

    if ($item) {
        $media = $attachment->media() ?: $item->primaryMedia();
    }

    $caption = $attachment->caption();
?>
<div id="block-<?php echo $this->blockId; ?>" class="profile-picture region <?php echo $this->thumbnailType; ?> <?php echo $this->regionClass; ?>" data-target-region-id="<?php echo $this->targetID; ?>">
    <div class="item resource">
        <?php if ($media): ?>
            <figure>
                <?php if (isset($this->block->page_title) && isset($this->block->page_url)): ?>
                  <?php printf('<a href="%s" title="Visit %s’s Profile">%s</a>',$this->block->page_url, $this->block->page_title, $this->thumbnail($media,$thumbnailType));  ?>
                <?php else: ?>
                  <?php echo $item->linkRaw($this->thumbnail($media,$thumbnailType)); ?>
                <?php endif; ?>
                <?php if ($caption): ?>
                    <figcaption>
                      <?php if ($this->title): ?>
                        <h1><?php echo $title; ?>
                      <?php endif; ?>
                      <?php echo $caption; ?>
                      <img class="profile-overlay-logo" src="../../../themes/huronia/asset/img/svg/marks/logo_black.svg" alt="Huronia logo">
                      <?php if (isset($this->block->page_title) && isset($this->block->page_url)): ?>
                        <a href='<?php echo $this->block->page_url; ?>' title='Profile Page' class='btn-outline profile-overlay-btn'>See <?php echo $this->block->page_title; ?>'s Profile</a>
                    <?php else: ?>
                        <a href='<?php echo $item->linkRaw($this->thumbnail($media,$thumbnailType)); ?>' title='Profile Page' class='btn-outline profile-overlay-btn'>View Larger Image</a>
                        
                    <?php endif; ?>
                      <div class="scroll-down">
                          <a class='down-arrow' href="#main-content" alt='Scroll down to see content'>
                              <img src="./../../../themes/huronia/asset/img/svg/icons/down_chevron_fire.svg" alt="Down arrow">
                              <span>Scroll Down</span>
                          </a>
                      </div>
                    </figcaption>
                <?php endif; ?>
            </figure>
        <?php endif; ?>
    </div>
</div>
