<?php
$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');
$this->htmlElement('body')->appendAttribute('class', 'item resource browse');

$query = $this->params()->fromQuery();
$itemSetShow = isset($itemSet);
if ($itemSetShow):
    $this->htmlElement('body')->appendAttribute('class', 'item-set');
    $query['item_set_id'] = $itemSet->id();
endif;
$headingTerm = $this->siteSetting('browse_heading_property_term', 'dcterms:title');
$bodyTerm = $this->siteSetting('browse_body_property_term', 'dcterms:description');
$sortHeadings = [
    [
        'label' => $translate('Title'),
        'value' => 'dcterms:title'
    ],
    [
        'label' => $translate('Identifier'),
        'value' => 'dcterms:identifier'
    ],
    [
        'label' => $translate('Class'),
        'value' => 'resource_class_label'
    ],
    [
        'label' => $translate('Created'),
        'value' => 'created'
    ],
];
?>

<?php if ($itemSetShow): ?>
    <?php echo $this->pageTitle($itemSet->displayTitle(), 2); ?>
    <h3><?php echo $translate('Item set'); ?></h3>
    <div class="metadata">
        <?php echo $itemSet->displayValues(); ?>
    </div>
    <div class="item-set-items">
    <?php echo '<h3>' . $escape($translate('Items')) . '</h3>'; ?>
<?php else: ?>
    <div class="explore-the-archive">
        <div>
            <h1>Explore the Archive</h1>
            <p>The archive is an historical repository and is not built to act in the service of ongoing projects, 
                so it is not able to provide links to ongoing activist/scholarly work. 
            </p>
            <div class="explore-warning">
                <img src="<?php echo $this->assetUrl('img/svg/icons/warning_red.svg'); ?>" title="Warning">
                <div> 
                    <h6>Warning</h6>
                    <p>
                        All information received will be treated in accordance 
                        with the Freedom of Information and Protection of Privacy Act (FIPPA). 
                    </p>
                </div>
            </div>
        </div>
        <div id="search"><?php echo $this->partial('common/search-form'); ?></div>
        <?php echo $this->hyperlink($translate('Use advanced search'), $this->url('site/resource', ['controller' => 'item', 'action' => 'search'], ['query' => $query], true), ['class' => 'advanced-search']); ?>
        <h3>Browse Items </h3>
    </div>
<?php endif; ?>

<?php echo $this->searchFilters(); ?>

<div class="browse-controls">
    <?php echo $this->pagination(); ?>
    <?php echo $this->sortSelector($sortHeadings); ?>
</div>

<?php $this->trigger('view.browse.before'); ?>
<ul class="resource-list">
<?php
foreach ($items as $item):
    $heading = $item->value($headingTerm, ['default' => $translate('[Untitled]')]);
    $body = $item->value($bodyTerm);
?>
    <li class="item resource">
        <?php echo $item->linkRaw($this->thumbnail($item, 'medium')); ?>
        <h4><?php echo $item->link($heading); ?></h4>
        <?php if ($body): ?>
        <div class="description"><?php echo $body; ?></div>
        <?php endif; ?>
    </li>
<?php endforeach; ?>
</ul>
<?php echo ($itemSetShow) ? '</div>' : ''; ?>
<?php $this->trigger('view.browse.after'); ?>
<?php echo $this->pagination(); ?>
