<?php
$altText = $media->jsonSerialize()['o-module-alt-text:alt-text'];
?>
<fieldset id="alt-text-section" class="section">
    <legend id="mapping-legend"><?php echo $this->translate('Alt Text'); ?></legend>
    <div class="field">
        <div class="field-meta">
            <label for="alt-text"><?php echo $this->translate('Alt Text'); ?></label>
        </div>
        <div class="inputs">
            <div>
                <textarea name="o-module-alt-text:alt-text" id="alt-text" rows="4"><?php echo $this->escapeHtml($altText); ?></textarea>
            </div>
        </div>
    </div>
</fieldset>
