<?php
$this->headLink()->appendStylesheet($this->assetUrl('css/page-blocks.css', 'Omeka'));
$this->htmlElement('body')->appendAttribute('class', $pageBodyClass);
$this->pageTitle($page->title(), 2);
$nav = $site->publicNav();
$activePage = $nav->findActive($nav->getContainer());
switch ($this->siteSetting('subnav_display')) {
    case 'show';
        $displaySubnav = $this->displayNavigation;
        break;
    case 'hide':
        $displaySubnav = false;
        break;
    default:
        $displaySubnav = $this->displayNavigation && $activePage && $activePage['page']->hasPages();
}
$showPagePagination = $this->siteSetting('show_page_pagination', true);
?>

<?php $this->trigger('view.show.before'); ?>

<?php echo $this->content; ?>

<?php $this->trigger('view.show.after'); ?>
<?php if ($showPagePagination): ?>
<?php echo $this->sitePagePagination(); ?>
<?php endif; ?>
