<div id="homepage-splash" class="block-<?php echo $this->blockId; ?> region <?php echo $this->regionClass; ?>" data-target-region-id="<?php echo $this->targetID; ?>">
    <div class="items">
        <?php foreach ($attachments as $attachment): ?>
            <?php
                $item = $attachment->item();
            ?>
            <div class="item resource">
                <?php if ($item):
                    $title = $this->plugin('escapeHtml')($item->displayTitle());
                    $media = $attachment->media() ?: $item->primaryMedia();
                    if ($media):
                        $image = preg_match('/alt=""/', $this->thumbnail($media, $this->thumbnailType)) == 1 ? $item->linkRaw($this->thumbnail($media, $this->thumbnailType, ['alt' => $title])) : $item->linkRaw($this->thumbnail($media, $this->thumbnailType, ['alt' => 'foo']));

                ?>
                        <figure>
                            <?php echo $image; ?>
                            <?php if ($attachment->caption()): ?>
                              <figcaption><?php echo $attachment->caption(); ?></figcaption>
                            <?php endif; ?>
                        </figure>
                    <?php endif; ?>
                <?php endif; ?>
            </div>
        <?php endforeach; ?>
    </div>
   

    <div class="item resource introduction">
        <div class='introductory-text'>
            <?php if (!empty($titleSlideTitle)): ?>
                <h1><?php echo $titleSlideTitle; ?></h1>
            <?php endif; ?>
            <?php if (!empty($titleSlideIntro)): ?>
                <?php echo $titleSlideIntro; ?>
            <?php endif; ?>
        </div>
    </div>
</div>
