<div id="block-<?php echo $this->blockId; ?>" class="section-intro-splash region <?php echo $this->regionClass; ?>  <?php echo $titleSlideTextAlignment ?>" data-target-region-id="<?php echo $this->targetID; ?> ">
    <div class="items">
        <?php foreach ($attachments as $key => $attachment): ?>
            <?php
                $item = $attachment->item();
            ?>
            <div class="item resource<?php foreach ($attachmentOptions as $attachmentOption => $defaultVal) {echo ' slide-' . $attachmentOption . '-' . ${'attachment' . ucfirst($attachmentOption)}[$key];}?>">
                <?php if ($item):
                    $title = $this->plugin('escapeHtml')($item->displayTitle());
                    $media = $attachment->media() ?: $item->primaryMedia();
                    if ($media):
                        $image = preg_match('/alt=""/', $this->thumbnail($media, $attachmentSize[$key])) == 1 ? $item->linkRaw($this->thumbnail($media, $attachmentSize[$key], ['alt' => $title])) : $item->linkRaw($this->thumbnail($media, $attachmentSize[$key]));
                ?>
                      <figure>
                          
                          <?php echo $image; ?>
                          <?php if ($attachment->caption()): ?>
                            <figcaption><?php echo $attachment->caption(); ?></figcaption>
                          <?php endif; ?>
                      </figure>
                    <?php endif; ?>
                <?php endif; ?>
            </div>
        <?php endforeach; ?>
    </div>
    <div class="item resource introduction">
        <div class='introductory-text'>
            <?php if (!empty($titleSlideTitle)): ?>
                <h1><?php echo $titleSlideTitle; ?></h1>
            <?php endif; ?>
            <div class="break white"></div>
            <?php if (!empty($titleSlideIntro)): ?>
                <?php echo $titleSlideIntro; ?>
            <?php endif; ?>
        </div>
    </div>
</div>


