<?php
    $style = '';

    if ($attachment !== false) {
        $item = $attachment->item();

        $media = null;

        if ($item) {
            $media = $attachment->media() ?: $item->primaryMedia();

            if($media) {
                $styleAttr = 'style="background-image: url(' . $media->thumbnailUrl('large') . ')"';
            }
        }

        $caption = $attachment->caption();

    }

?>
<div id="block-<?php echo $this->blockId; ?>" class="poster region <?php echo $this->thumbnailType; ?> <?php echo $this->regionClass; ?> <?php echo $this->colourScheme; ?> <?php echo $this->textTreatment; ?>" data-target-region-id="<?php echo $this->targetID; ?>">
    <div class="poster-text">
        <?php echo $this->html; ?>
    </div>
    <?php if ($attachment !== false && $media): ?>
        <div class="image-background item resource" <?php echo $styleAttr; ?>>
        </div>
    <?php endif; ?>

</div>
