<?php
$itemCount = count($this->pages);

?>
<div id="block-<?php echo $this->blockId; ?>" class="compact-card-listing item-count-<?php echo $itemCount; ?> <?php echo $this->regionClass; ?> <?php echo $this->classes ?>" data-target-region-id="<?php echo $this->targetID; ?>">
    <?php if ($this->hasTitle || $this->hasIntroduction): ?>
        <div class='title-area'>
            <?php if ($this->hasTitle): ?>
                <h2><?php echo $this->title; ?></h2>
            <?php endif; ?>
            <?php if ($this->hasIntroduction): ?>
                <div class='block-introduction'>
                    <?php echo $this->introduction; ?>
                </div>
            <?php endif; ?>
            <?php if ($this->hasButton): ?>
                <?php printf('<a class="btn" href="%s" alt="%s">%s</a>',$this->buttonPath,$this->buttonText,$this->buttonText); ?>
            <?php endif; ?>
        </div>
    <?php endif; ?>
    <?php if ($this->hasPages): ?>
        <?php foreach($this->pages as $page): ?>
            <div class="card-compact">
                <?php if ($page['hasEmbeddedBlocks'] && array_key_exists('representativeImage',$page['embeddedBlocks'])): ?>
                    <?php echo $page['embeddedBlocks']['representativeImage'][0]; ?>
                <?php endif; ?>
                <h3><a href='<?php echo $page['o:url']; ?>'><?php echo $page['o:title']; ?></a></h3>
            </div>
        <?php endforeach; ?>
    <?php endif; ?>
</div>