<?php
    $item = $attachment->item();

    $media = null;

    if ($item) {
        $media = $attachment->media() ?: $item->primaryMedia();
    }

    $caption = $attachment->caption();
?>
<div id="block-<?php echo $this->blockId; ?>" class="poster region <?php echo $this->thumbnailType; ?> <?php echo $this->regionClass; ?> <?php echo $this->colourScheme; ?>" data-target-region-id="<?php echo $this->targetID; ?>">
    <div class="poster-text">
        <?php echo $this->html; ?>
    </div>
    <div class="image-background item resource">
        <?php if ($media): ?>
            <figure>
                <?php if (isset($this->block->page_title) && isset($this->block->page_url)): ?>
                  <?php printf('<a href="%s" title="Visit %s’s Profile">%s</a>',$this->block->page_url, $this->block->page_title, $this->thumbnail($media,$thumbnailType));  ?>
                <?php else: ?>
                  <?php echo $item->linkRaw($this->thumbnail($media,$thumbnailType)); ?>
                <?php endif; ?>
            </figure>
        <?php endif; ?>
    </div>
</div>
