<?php
$escape = $this->plugin('escapeHtml');
$this->htmlElement('html')->setAttribute('lang', $this->lang());
$this->headMeta()->setCharset('utf-8');
$this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1');
$this->headTitle($this->setting('installation_title', 'Omeka S'))->setSeparator(' · ');
$this->headLink()->prependStylesheet($this->assetUrl('css/vendor.min.css'));
$this->headLink()->prependStylesheet($this->assetUrl('css/iconfonts.css', 'Omeka'));
$this->headLink()->appendStylesheet($this->assetUrl('css/style.min.css'));

$this->headScript()->prependFile($this->assetUrl('js/default.js'));
$this->headScript()->prependFile($this->assetUrl('js/global.js', 'Omeka'));
$this->headScript()->prependFile($this->assetUrl('js/vendor.min.js'));
$this->headScript()->prependFile($this->assetUrl('vendor/jquery/jquery.min.js', 'Omeka'));


$this->trigger('view.layout');
$title = $this->pageTitle($site->title());
$userBar = $this->userBar();

$nav = $site->publicNav();
$container = $nav->getContainer();
$activePage = $nav->findActive($container);
$pageClass = null;

if ($activePage && array_key_exists('page-slug',$activePage['page']->getParams())) {
    $slug = $activePage['page']->getParams()['page-slug'];
    $classes = array('collections', 'profiles', 'exhibits', 'about-huronia');

    $pageClass = '';

    foreach ($classes as $class) {
        if (strpos($slug, $class) !== false) {
            $pageClass = $pageClass . ' ' . $class;
            break;
        }
    }
}
?>
<?php echo $this->doctype(); ?>
<?php echo $this->htmlElement('html'); ?>
    <head>
        <?php echo $this->headMeta(); ?>
        <?php echo $this->headTitle(); ?>
        <?php echo $this->headLink(); ?>
        <?php echo $this->headStyle(); ?>
        <?php echo $this->headScript(); ?>

    </head>

    <?php echo $pageClass ? $this->htmlElement('body')->appendAttribute('class', $pageClass) : $this->htmlElement('body'); ?>
        <div class="full"><?php echo $userBar; ?> </div>
        <header class="full">
            <a id='logo-stack' href="<?php echo $site->url(); ?>" class="site-title history-identity" title="Link to homepage"><img src="<?php echo $this->assetUrl('img/svg/marks/circle_white.svg'); ?>" alt=" Logo"> Dartmouth Historical Accountability Program</a>
            <nav class="desktop-nav">
                <?php echo $this->navigation($this->subNav)->menu()->renderMenu($container, ['maxDepth' =>2]); ?>
            </nav>
            <a class="menu-access-button" href="#">
                <span>
                  
                    <i class="down-arrow-black"></i>
                </span>
            </a>
            
        </header>
       
        <nav class="access-dropdown-mobile" style="display:none" aria-hidden='true'>
                <?php echo $this->navigation($this->subNav)->menu()->renderMenu($container, ['maxDepth' =>2]); ?>
                <ul>
                    <li class="mobile-switch-pos"><label class="dark-switch">
                            <input type="checkbox" aria-labelledby='darkmode-mobile-togglelabel'>
                            <span class="slider round"></span>
                            <span id='darkmode-mobile-togglelabel' class="toggle-label">Dark Mode</span>
                        </label>
                        
                    </li>
                </ul>
        </nav>
        <section id='splash' class='full'></section>
        <section id='primary-content' class='full'>
            <a name='main-content'></a>
            <main>
              <div id='content-stack' contentstack>
                <?php echo $this->content; ?>
              </div>
            </main>
        </section>
        <section id='feature-tier-1' class='full'></section>
        <section id='feature-tier-2' class='full'></section>
        <section id='feature-tier-3' class='full'></section>
        <section class='full'>
            <div>
            <div id='secondary-content' style="display:none"></div>
            </div>
        </section>
        <footer class="full">
            <div>
                <a href="<?php echo $site->url(); ?>" class="footer--recountlogo" title='Link to homepage'>
                    <img src="<?php echo $this->assetUrl('img/svg/marks/around_white_mark.svg'); ?>" alt=" Logo">
                </a>
            </div>
            <div class="footer--text">
            <p>  
                    <?php if ( $footerText = $this->themeSetting('footer') ): ?>
                        <?php echo $footerText; ?>
                    <?php else: ?>
                        <p> Go to Theme > Edit Theme Settings > Footer Content to enter content here</p>
                    <?php endif; ?>
            </p>
            </div class="footer--links">
            <?php if ( $footerText = $this->themeSetting('footer_links') ): ?>
                <?php echo $footerText; ?>
            <?php else: ?>
                <nav>
                    <ul>
                        <li>LINKS</li>
                        <li><a href='#'>Link 1</a></li>
                        <li><a href='#'>Link 2</a></li>
                        <li><a href='#'>Link 3</a></li>
                        <li><a href='#'>Admin Login</a></li>
                    </ul>
                </nav>
            <?php endif; ?>
            <div class="footer--logo">
                <img src="<?php echo $this->assetUrl('img/svg/marks/text_only_mark.svg'); ?>" alt=" Badge Logo">
            </div>
        </footer>
    </body>
</html>
