<?php
$translate = $this->plugin('translate');
$searchValue = $this->escapeHtml($this->params()->fromQuery('search', ''));
?>

<form action="<?php echo $this->escapeHtml($this->url('site/resource', ['controller' => 'item','action' => 'browse'], true)); ?>" id="search-form">
    <input type="text" title='Search Field' name="search" value="<?php echo $searchValue; ?>" placeholder="<?php echo $translate('Enter a search term or browse below'); ?>">
    <button type="submit"><?php echo $translate('Search'); ?></button>
</form>
