<div class="value external-css-value">
    <div class="input-body">
        <input type="text" name="external-css[<?php echo $externalCssFieldCount; ?>]" aria-labelledby="external-css-label" value="<?php echo $externalCssValue; ?>" data-field-count="<?php echo $externalCssFieldCount; ?>">
    </div>
    <div class="input-footer">
        <ul class="actions">
            <li><a class="o-icon-delete remove-value" title="Remove value" href="#" aria-label="Remove value"></a></li>
        </ul>
    </div>
</div>